name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  image_picker: ^0.8.4+4

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  flutterfire_ui: ^0.4.3+20
  firebase_storage: ^11.2.2

  roulette: 0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/diamond.png
    - assets/logos/logo_black.png
    - assets/logos/logo_white.png


