// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHIyhsEWb5JUQFZM5dPcJBJkkzWn-P2A',
    appId: '1:267802070951:web:4c081f10d897cf6d4ab082',
    messagingSenderId: '267802070951',
    projectId: 'final-project-396a8',
    authDomain: 'final-project-396a8.firebaseapp.com',
    storageBucket: 'final-project-396a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnuV6otcvnwUYhmgAPIfEHR0jgStWdhU',
    appId: '1:267802070951:android:929e33b1ea0de3ad4ab082',
    messagingSenderId: '267802070951',
    projectId: 'final-project-396a8',
    storageBucket: 'final-project-396a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGrUQ2VxodDdjjhYpyx5whfKxIRKnKmc',
    appId: '1:267802070951:ios:0ccb6001a019ea504ab082',
    messagingSenderId: '267802070951',
    projectId: 'final-project-396a8',
    storageBucket: 'final-project-396a8.appspot.com',
    iosClientId: '267802070951-3oi0fgbf7popojk7nq527k6cab9qp3jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGrUQ2VxodDdjjhYpyx5whfKxIRKnKmc',
    appId: '1:267802070951:ios:0ccb6001a019ea504ab082',
    messagingSenderId: '267802070951',
    projectId: 'final-project-396a8',
    storageBucket: 'final-project-396a8.appspot.com',
    iosClientId: '267802070951-3oi0fgbf7popojk7nq527k6cab9qp3jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );
}
